services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyUserDemo\:
        resource: '../../{Command,Repository,Service}'
        exclude: '../../Service/**/Abstract*.php'

    Wexample\SymfonyUserDemo\Controller\:
        resource: '../../Controller/'
        exclude: '../../Controller/**/Abstract*.php'
        tags: ['controller.service_arguments']
